#!/usr/bin/python3
import os
import subprocess
import sys

def app():
	confTemplate = """
config = {
	'KeyFolderName':''
}
"""
	
	
	def getHomeDir():
		homedir = os.environ['HOME']
		return homedir

	getDir = getHomeDir()

	def firstRun():
		try:
			os.mkdir("/etc/sshmaker")
			confFile = open('/etc/sshmaker/config.py', 'w+')
			confFile.write(confTemplate)
			sys.path.insert(0, "/dev/sshmaker")
			import config
		except FileExistsError:
			print("Reading config /etc/sshmaker")
		
	def readConfig():
		configFile = open("{}/.sshmaker-config.py".format(getDir), "r")
		configFileRead = configFile.read()

		global x
		x = configFileRead

		configFile.close()

	firstRun()
	readConfig()

	def questions():
		global host,port,name,user

		host = input("Enter hostname of system: ")
		port = input("Enter port of ssh server: ")
		name = input("Enter name of system: ")
		user = input("Enter user: ")

	def keyFileYN():
		global keyFileN 
		yn = input("Would you like to connect with a key file? [Y] [N]: ").lower()


		if yn == "y":
			keyFile = input("Enter key file name: ")
			keyFileN = "-i {}/{}".format(x, keyFile)
		elif yn == "n":
			keyFileN = ""
		else:
			print("You didn't enter y or n")
			keyFileYN()

	questions()
	keyFileYN()

	f = open("{}/{}".format(getDir, name), "w+")

	f.write("#!/bin/bash\nssh "+user+"@"+host+" -p "+port+" {}".format(keyFileN))
	f.close()


	perms = 'sudo chmod +x {}/{}'.format(getDir, name)

	print("\nSudo is needed to change perms of file to make executable.\n")
	os.system(perms)

	print("Bash script {} created.".format(name))


if sys.platform == "linux" or sys.platform == "linux2":
	if os.getuid() == "0" or os.getuid() == 0:
		app()
	else:
		print("Program must be run as sudo")
else:
	print("This program only works on linux but can be easily modified to work on other OSs")
