#!/usr/bin/python3
import os

def firstRun():
	#Test if config exists
	try:
		configFile = open("./.sshmaker-config", "r")
	except FileNotFoundError:
		#If it doesn't, create one and ask for path to ssh key folder
		keyFolder = input("Enter path to key folder e.g: /home/user/ssh_keys: ")
		
		configFile = open("./.sshmaker-config", "w+")
		configFile.write("{}".format(keyFolder))
	
	configFile.close()

def readConfig():
	configFile = open("./.sshmaker-config", "r")
	configFileRead = configFile.read()

	global x
	x = configFileRead

	configFile.close()

firstRun()
readConfig()


host = input("Enter hostname of system: ")
port = input("Enter port of ssh server: ")
name = input("Enter name of system: ")
user = input("Enter user: ")
yn = input("Would you like to connect with a key file? [Y] [N]: ").lower()

def keyFileYN():
        global keyFileN      

        if yn == "y":
	        keyFile = input("Enter key file name: ")
                keyFileN = "-i {}/{}".format(x,keyFile)
        elif yn == "n":
	        keyFile = ""
        else:
                print("You didnt enter y or n")
                keyFileYN()

keyFileYN()

f = open("./{}".format(name), "w+")

f.write("#!/bin/bash\nssh "+user+"@"+host+" -p "+port+" {}".format(keyFileN))

f.close()

perms = 'sudo chmod +x ./{}'.format(name)

os.system(perms)
