#!/usr/bin/python3
import os
import sys

def argvs()
        global name, port, user, host	
	try:

		if sys.argv[1] == "-p":
			port = sys.argv[2]
		elif sys.argv[1] == "-n":
			name = sys.argv[2]
		elif sys.argv[1] == "-h":
			host = sys.argv[2]
		elif sys.argv[1] == "-u":
			user = sys.argv[2]
		
		if sys.argv[3] == "-p":
			port = sys.argv[4]
		elif sys.argv[3] == "-n":
			name = sys.argv[4]
		elif sys.argv[3] == "-h":
			host = sys.argv[4]
		elif sys.argv[3] == "-u":
			user = sys.argv[4]
		
		if sys.argv[5] == "-p":
			port = sys.argv[6]
		elif sys.argv[5] == "-n":
			name = sys.argv[6]
		elif sys.argv[5] == "-h":
			host = sys.argv[6]
		elif sys.argv[5] == "-u":
			user = sys.argv[6]
		
		if sys.argv[7] == "-p":
			port = sys.argv[8]
		elif sys.argv[7] == "-n":
			name = sys.argv[8]
		elif sys.argv[7] == "-h":
			host = sys.argv[8]
		elif sys.argv[7] == "-u":
			user = sys.argv[8]

	except IndexError:
		print("no args")
		

	

def firstRun():
	#Test if config exists
	try:
		configFile = open("./.sshmaker-config", "r")
	except FileNotFoundError:
		#If it doesn't, create one and ask for path to ssh key folder
		keyFolder = input("Enter path to key folder e.g: /home/user/ssh_keys: ")
		
		configFile = open("./.sshmaker-config", "w+")
		configFile.write("{}".format(keyFolder))
	
	configFile.close()

def readConfig():
	configFile = open("./.sshmaker-config", "r")
	configFileRead = configFile.read()

	global x
	x = configFileRead

	configFile.close()

firstRun()
readConfig()

def questions():
	global host,port,name,user

	host = input("Enter hostname of system: ")
	port = input("Enter port of ssh server: ")
	name = input("Enter name of system: ")
	user = input("Enter user: ")

argvs()

if host == "" or port == "" or name == "" or user == "":
	questions()

def keyFileYN():
	global keyFileN 
	yn = input("Would you like to connect with a key file? [Y] [N]: ").lower()


	if yn == "y":
		keyFile = input("Enter key file name: ")
		keyFileN = "-i {}/{}".format(x, keyFile)
	elif yn == "n":
		keyFileN = ""
	else:
		print("You didn't enter y or n")
		keyFileYN()


keyFileYN()

f = open("./{}".format(name), "w+")

f.write("#!/bin/bash\nssh "+user+"@"+host+" -p "+port+" {}".format(keyFileN))
f.close()


perms = 'sudo chmod +x ./{}'.format(name)

print("sudo is needed to change perms of file to make executable.")
os.system(perms)

print("Bash script {} created.".format(name))
